name: Node.js Package in Docker

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: node:18
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test

      - name: Publish to npm
        if: github.event_name == 'release' && github.event.action == 'created'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
